apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-go-api
  namespace: dev-go-api
  labels:
    app:  dev-go-api
spec:
  selector:
    matchLabels:
      app:  dev-go-api
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dev-go-api
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: dev-go-api
        image:  anibalvy/go-api-skel:dev
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            # path: /_status/healthz
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
          periodSeconds: 15
        # env:
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name:
        #       key: DB_HOST
        # envFrom:
        # - configMapRef:
        #     name: dev-go-api
        # - secretRef:
        #   name: dev-go-api-secrets

        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: env
          mountPath: /.env
          subPath: .env
      #   volumeMounts:
      #   - name: localtime
      #     mountPath: /etc/localtime
      volumes:
        - name: env
          configMap:
            name: dev-go-api


      # volumes:
      #   - name: localtime
      #     hostPath:
      #       path: /usr/share/zoneinfo/Asia/Taipei
      # restartPolicy: Always
---

