---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    # targetRevision: 3.8.4
    targetRevision: 3.11.0
    chart: metrics-server
    helm:
      version: v3
      releaseName: my-metrics
      passCredentials: false  # if the chart needs credentials
      parameters:   # override defaults params
        - name: "image.tag"
          value: v0.6.2
#       # up to change specific values
#       # but down, we can add a yml file to better do it
      values: |
        defaultArgs:
        - --cert-dir=/tmp
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --kubelet-use-node-status-port
        - --metric-resolution=15s
        - --kubelet-insecure-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - allowEmpty=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

